version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    ports:
    - 9200:9200
    environment:
    - cluster.name=es
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    ports:
    - 5601:5601
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - TELEMETRY_ENABLED=false
    depends_on:
    - elasticsearch
